//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GibddApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverVehicle
    {
        public int DriverVehicleId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public string VehicleVin { get; set; }
        public Nullable<int> VehicleManufacter { get; set; }
        public Nullable<int> VehicleSerial { get; set; }
        public Nullable<int> VehicleModel { get; set; }
        public string VehicleYear { get; set; }
        public string VehicleWeight { get; set; }
        public Nullable<int> VehicleColor { get; set; }
        public Nullable<int> EngineType { get; set; }
        public Nullable<int> DriveType { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual DriveType DriveType1 { get; set; }
        public virtual Manufacter Manufacter { get; set; }
        public virtual Model Model { get; set; }
        public virtual Serial Serial { get; set; }
    }
}
