//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GibddApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Licence()
        {
            this.LicenceCategory = new HashSet<LicenceCategory>();
        }
    
        public int LicenceId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public System.DateTime LicenceDate { get; set; }
        public System.DateTime LicenceExpireDate { get; set; }
        public string LicenceSeries { get; set; }
        public string LicenceNumber { get; set; }
        public Nullable<int> LicenceStatus { get; set; }
        public string LicenceStampPath { get; set; }
        public string LicenceDriverSignature { get; set; }
        public string LicenceInfoForChangingCountry { get; set; }
        public string LicenceAdditionalInfo { get; set; }
    
        public virtual CategoryStatus CategoryStatus { get; set; }
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LicenceCategory> LicenceCategory { get; set; }
    }
}
