//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GibddApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenceArchive
    {
        public int LicenceArchiveId { get; set; }
        public int LicenceId { get; set; }
        public int DriverId { get; set; }
        public System.DateTime LicenceDate { get; set; }
        public System.DateTime LicenceExpireDate { get; set; }
        public string LicenceSeries { get; set; }
        public string LicenceNumber { get; set; }
        public int LicenceStatus { get; set; }
        public string LicenceStampPath { get; set; }
        public string LicenceDriverSignature { get; set; }
        public string LicenceInfoForChangingCountry { get; set; }
        public string LicenceAdditionalInfo { get; set; }
    }
}
