//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GibddApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenceCategory
    {
        public int LicenceCategoryId { get; set; }
        public Nullable<int> LicenceId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string Constraints { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Licence Licence { get; set; }
    }
}
